import { randomBytes, scrypt as scryptCb, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';

const scrypt = promisify(scryptCb) as (
  password: string | Buffer,
  salt: string | Buffer,
  keylen: number,
  options: { N: number; r: number; p: number; maxmem: number },
) => Promise<Buffer>;

/**
 * The username: the PUBLIC identity, chosen by the user.
 *
 * The reason a separate public identity exists at all is the load-bearing part of the whole design:
 * the credential is a secret, and vMCP's dashboard prints user ids on a publicly-readable API.
 * Whatever is shown there must be safe to show a stranger. So the user is known by a name they
 * picked, and proves it with a secret nobody ever sees. See DESIGN.md §2.
 *
 * Rules: 3–20 characters, lowercase letters, digits, `_` and `-`. No leading or trailing separator.
 * Case-insensitive for uniqueness, so `Andres` and `andres` cannot both exist — otherwise the
 * username would be an impersonation vector rather than an identity.
 */
const USERNAME_RE = /^[a-z0-9](?:[a-z0-9_-]{1,18}[a-z0-9])?$/;

export function normaliseUsername(input: string): string {
  return input.trim().toLowerCase();
}

export function isValidUsername(name: string): boolean {
  return name.length >= 3 && name.length <= 20 && USERNAME_RE.test(name);
}

/**
 * The password: the SECRET, now chosen by the user rather than generated by the server.
 *
 * That change is the whole point of this enhancement, and it moves the keyspace argument off the
 * server and onto the user. The old 7-character code was uniform over 34 billion values; a chosen
 * password is whatever the user picks, and people pick badly. So the defences shift accordingly:
 *
 *   - a MINIMUM LENGTH, the only floor we can enforce on entropy without hosting a wordlist;
 *   - a SLOW hash (scrypt), so an offline dump cannot be dictionary-attacked at billions/sec the way
 *     a fast HMAC could have been, had the credential not been high-entropy;
 *   - a PER-USER SALT, so one cracked password does not crack the rest and identical passwords do
 *     not collide to identical hashes;
 *   - the PEPPER, kept from the old design — folded into the hash input so a stolen database dump is
 *     useless without a secret that never lives in the database. Salt defends users from each other;
 *     the pepper defends all of them from a dump.
 *
 * Rate limiting (routes/auth.ts) remains the only online defence, exactly as before.
 */

/** 4–128 characters. The lower bound is the real defence now that the user chooses this; the upper
 *  bound bounds the work scrypt is asked to do on attacker-supplied input. */
const PW_MIN = 4;
const PW_MAX = 128;

export function isValidPassword(pw: unknown): pw is string {
  return typeof pw === 'string' && pw.length >= PW_MIN && pw.length <= PW_MAX;
}

/**
 * scrypt parameters. N is the CPU/memory cost; 2^15 with r=8, p=1 is a common interactive-login
 * target and needs ~32 MiB per hash, which `maxmem` must clear or scrypt throws. They are written
 * INTO each stored hash below, so raising them later still verifies every password hashed under the
 * old ones — a hash is self-describing, and upgrading is a policy change, not a migration.
 */
const N = 2 ** 15;
const R = 8;
const P = 1;
const KEYLEN = 32;
const MAXMEM = 64 * 1024 * 1024;
const SALT_BYTES = 16;

/**
 * What we store instead of the password: `scrypt$N$r$p$salt$hash`, base64url throughout.
 *
 * The pepper is prepended to the password before hashing. It is NOT the salt — the salt is stored
 * beside the hash and defends users from one another; the pepper is a single secret held outside the
 * database (a sealed secret) and defends every user from a dump. An attacker with the table has the
 * salts and still cannot begin without the pepper.
 */
export async function hashPassword(password: string, pepper: string): Promise<string> {
  const salt = randomBytes(SALT_BYTES);
  const derived = await scrypt(pepper + password, salt, KEYLEN, { N, r: R, p: P, maxmem: MAXMEM });
  return `scrypt$${N}$${R}$${P}$${salt.toString('base64url')}$${derived.toString('base64url')}`;
}

/**
 * Verify a candidate password against a stored hash. Re-derives with the SAME parameters and salt the
 * stored value records, then compares in constant time so a near-match cannot be distinguished from a
 * far one by how long the comparison took. Any malformed stored value is a false, never a throw — a
 * corrupt row must read as "wrong password", not crash the login path.
 */
export async function verifyPassword(stored: string, password: string, pepper: string): Promise<boolean> {
  const parts = stored.split('$');
  if (parts.length !== 6 || parts[0] !== 'scrypt') return false;
  const [, nStr, rStr, pStr, saltB64, hashB64] = parts;
  if (saltB64 === undefined || hashB64 === undefined) return false;
  const n = Number(nStr);
  const r = Number(rStr);
  const p = Number(pStr);
  if (!Number.isInteger(n) || !Number.isInteger(r) || !Number.isInteger(p)) return false;

  let expected: Buffer;
  let actual: Buffer;
  try {
    expected = Buffer.from(hashB64, 'base64url');
    const salt = Buffer.from(saltB64, 'base64url');
    actual = await scrypt(pepper + password, salt, expected.length, { N: n, r, p, maxmem: MAXMEM });
  } catch {
    return false;
  }
  if (expected.length !== actual.length) return false;
  return timingSafeEqual(expected, actual);
}
