import { randomBytes, scrypt as scryptCb, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';

const scrypt = promisify(scryptCb) as (
  password: string | Buffer,
  salt: string | Buffer,
  keylen: number,
  options: { N: number; r: number; p: number; maxmem: number },
) => Promise<Buffer>;

/**
 * The username: the PUBLIC identity, chosen by the user. A separate public identity exists because the
 * credential is a secret and vMCP's dashboard prints user ids on a publicly-readable API, so whatever
 * is shown there must be safe for a stranger. See DESIGN.md §2.
 *
 * Rules: 3–20 chars, lowercase letters, digits, `_` and `-`, no leading/trailing separator.
 * Case-insensitive for uniqueness, so `Andres` and `andres` can't both exist (else it's an
 * impersonation vector, not an identity).
 */
const USERNAME_RE = /^[a-z0-9](?:[a-z0-9_-]{1,18}[a-z0-9])?$/;

export function normaliseUsername(input: string): string {
  return input.trim().toLowerCase();
}

export function isValidUsername(name: string): boolean {
  return name.length >= 3 && name.length <= 20 && USERNAME_RE.test(name);
}

/**
 * The password: the SECRET, now chosen by the user, not generated by the server. That moves the
 * keyspace argument onto the user, who picks badly (the old code was uniform over 34 billion), so the
 * defences shift:
 *
 *   - a MINIMUM LENGTH, the only entropy floor we can enforce without a wordlist;
 *   - a SLOW hash (scrypt), so an offline dump can't be dictionary-attacked at billions/sec;
 *   - a PER-USER SALT, so one cracked password doesn't crack the rest and equal passwords don't
 *     collide to equal hashes;
 *   - the PEPPER (kept from the old design), folded into the hash input so a stolen dump is useless
 *     without a secret never in the database. Salt defends users from each other, pepper from a dump.
 *
 * Rate limiting (routes/auth.ts) remains the only online defence.
 */

/** 4–128 characters. The lower bound is the real defence now that the user chooses this; the upper
 *  bound bounds the work scrypt is asked to do on attacker-supplied input. */
const PW_MIN = 4;
const PW_MAX = 128;

export function isValidPassword(pw: unknown): pw is string {
  return typeof pw === 'string' && pw.length >= PW_MIN && pw.length <= PW_MAX;
}

/**
 * scrypt parameters. N is the CPU/memory cost; 2^15 with r=8, p=1 targets interactive login and needs
 * ~32 MiB per hash, which `maxmem` must clear or scrypt throws. Written INTO each stored hash below, so
 * raising them later still verifies old passwords — a hash is self-describing, upgrading is not a migration.
 */
const N = 2 ** 15;
const R = 8;
const P = 1;
const KEYLEN = 32;
const MAXMEM = 64 * 1024 * 1024;
const SALT_BYTES = 16;

/** Field 0 of every stored hash: the KDF label that says how to read the rest. One source, so the
 *  writer's prefix and the verifier's guard can never name two different schemes. */
const SCHEME = 'scrypt';

/**
 * What we store instead of the password: `scrypt$N$r$p$salt$hash`, base64url throughout. The pepper is
 * prepended before hashing — NOT the salt: the salt is stored beside the hash (defends users from each
 * other), the pepper is a sealed secret outside the database (defends all from a dump). An attacker
 * with the table has the salts and still can't begin without the pepper.
 */
export async function hashPassword(password: string, pepper: string): Promise<string> {
  const salt = randomBytes(SALT_BYTES);
  const derived = await scrypt(pepper + password, salt, KEYLEN, { N, r: R, p: P, maxmem: MAXMEM });
  return `${SCHEME}$${N}$${R}$${P}$${salt.toString('base64url')}$${derived.toString('base64url')}`;
}

/**
 * Verify a candidate against a stored hash: re-derive with the SAME parameters and salt the stored
 * value records, then compare in constant time so a near-match can't be told from a far one by timing.
 * Any malformed stored value is false, never a throw — a corrupt row reads as "wrong password".
 */
export async function verifyPassword(stored: string, password: string, pepper: string): Promise<boolean> {
  const parts = stored.split('$');
  if (parts.length !== 6 || parts[0] !== SCHEME) return false;
  const [, nStr, rStr, pStr, saltB64, hashB64] = parts;
  if (saltB64 === undefined || hashB64 === undefined) return false;
  const n = Number(nStr);
  const r = Number(rStr);
  const p = Number(pStr);
  if (!Number.isInteger(n) || !Number.isInteger(r) || !Number.isInteger(p)) return false;

  let expected: Buffer;
  let actual: Buffer;
  try {
    expected = Buffer.from(hashB64, 'base64url');
    const salt = Buffer.from(saltB64, 'base64url');
    actual = await scrypt(pepper + password, salt, expected.length, { N: n, r, p, maxmem: MAXMEM });
  } catch {
    return false;
  }
  if (expected.length !== actual.length) return false;
  return timingSafeEqual(expected, actual);
}
