import { boolean, index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * An identity. Three values, and keeping them distinct is the whole design (DESIGN.md §2):
 *
 *   id            the opaque, stable identity. This is the JWT's `sub`, and the foreign key every
 *                 other service stores. It is meaningless on its own.
 *   username      the PUBLIC identity, chosen by the user. Safe in a dashboard, a leaderboard, a log.
 *   passwordHash  scrypt(pepper + password, per-row salt), self-describing. The password ITSELF is
 *                 never stored, anywhere, in any form that can be read back — not by us, not by a
 *                 stolen dump, which additionally needs the pepper that never lives in this table.
 *
 * The password is now chosen by the user rather than generated by the server. There is still no
 * recovery: a reset would need an email, an email would be PII, and this identity is designed to
 * hold none. What changed is who picks the secret, not that a forgotten one is gone.
 */
export const identities = pgTable(
  'identities',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** The public identity, chosen by the user. Stored lowercase — see credential.ts for why case-
     *  insensitivity is a security property here and not a nicety. */
    username: text('username').notNull().unique(),
    /** scrypt(pepper + password, salt). Salted per row, so it is NOT unique and NOT the lookup key —
     *  login finds the row by `username` (unique, indexed) and then verifies. See credential.ts. */
    passwordHash: text('password_hash').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastSeen: timestamp('last_seen', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // Login is a single indexed read on the username — the unique constraint already backs it, but an
    // explicit index states the access path the login query depends on.
    byUsername: index('identities_username_idx').on(t.username),
  }),
);

/**
 * Every attempt to exchange a code for a token, successful or not.
 *
 * This is an audit trail, not a rate limiter — the limiter is in front of it and is in-process. The
 * table is what lets you answer "is someone walking the keyspace?" after the fact, which no
 * in-memory counter can, because the answer only becomes visible across a long window.
 *
 * It stores the IP and whether the attempt succeeded. It does NOT store the code that was tried:
 * logging failed credentials is how one user's typo becomes another user's credential sitting in
 * plaintext in a table.
 */
export const authAttempts = pgTable(
  'auth_attempts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ip: text('ip').notNull(),
    ok: boolean('ok').notNull(),
    at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    byAt: index('auth_attempts_at_idx').on(t.at),
    byIp: index('auth_attempts_ip_idx').on(t.ip),
  }),
);
